### ISSUE TITLE
Annotation quality of TV-Hand

### ISSUE THREAD

**Issue by edwardnguyen1705** [SupreethN/Hand-CNN#10]
Hi @SupreethN 
Thank you for sharing your research.
I am trying to visualize both the COCO-Hand and TV-Hand datasets. I observe that TV-Hand contains many low quality annotations (boxes, (xmin, xmax, ymin, ymax)), but you state in the paper that this dataset is manually labelled?

**Comment by SupreethN** [comment]
I think there is a mistake in README file. The annotations are in the form ```(x_min, y_min, x_max, y_max)```, not ```(x_min, x_max, y_min, y_max)```. 
Also, if you want tighter boxes, use the polygon annotations provided.

**Comment by edwardnguyen1705** [comment]
Hi @SupreethN 
Thank you. You are right.
