### ISSUE TITLE
Can't load model weights

### ISSUE THREAD

**Issue by smandal94** [SupreethN/Hand-CNN#12]
For line 63 in detect.py 'model.load_weights('./model/trained_model.h5', by_name=True)':
OSError: Unable to open file (unable to open file: name = './model/trained_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
When I change to 'model.load_weights('./model/trained_weights.h5', by_name=True)':
ValueError: Layer #292 (named "contextual__attention_1") expects 29 weight(s), but the saved weights have 15 element(s).

**Comment by sandhyacs** [comment]
hi, even i am getting the same error. did you resolve it @sayanxtreme

**Comment by SupreethN** [comment]
See https://github.com/SupreethN/Hand-CNN/issues/11
