### ISSUE TITLE
Which annotations in Coco hand big are reliable?

### ISSUE THREAD

**Issue by SuhelNaryal** [SupreethN/Hand-CNN#15]
Hello,
In the COCO Hand big dataset annotations readme, you mentioned " we obtained the COCO-Hand dataset that has 26499 images with a total of 45671 hands", however, there are 120000+ annotations in the file. So my question is Which annotations are the reliable ones?

**Comment by SupreethN** [comment]
Download the COCO-Hand data from [here](http://vision.cs.stonybrook.edu/~supreeth/COCO-Hand.zip).
You can find reliable annotations in the ```./COCO-Hand-Big/COCO-Hand-Big_annotations.txt```.
