### ISSUE TITLE
it seems the training phase takes much time?

### ISSUE THREAD

**Issue by visonpon** [SupreethN/Hand-CNN#5]
Hi, @SupreethN, when I train it from scratch(I set batch_size=1, gpu=1),  after two days, one epoch hasn't finished, I wonder how many GPUs you have used to train this huge networks. thanks~

**Comment by SupreethN** [comment]
No, we trained it using only one GPU (Titan X, 12 GB). It takes around 1000 to 1400 seconds per epoch.
