### ISSUE TITLE
Slow inference runtime?

### ISSUE THREAD

**Issue by hassony2** [SupreethN/Hand-CNN#6]
Hi !

Thank you for the great work !

I had a question about the inference time, do you have an indicative idea of how long a forward pass of your model takes ? (for instance on your Titan GPU, either on a single or a batch of images ?)

When I run your model (without any modification) on a V100 Tesla I obersve long runtimes (>2 seconds for a forward pass on a 456x256 image) for the line 

`result = model.detect([img], verbose=0)[0]` from [here](https://github.com/SupreethN/Hand-CNN/blob/389aece617439a3febc7162633e00eacaae98e82/detect.py#L91)

I am using the command `python -W ignore detect.py --image_dir /path/to/my/images`.

Thank you for any help you might provide!

All the best,

Yana

**Comment by SupreethN** [comment]
Hello. The inference time is around  2-3 frames/ second on Titan X.

**Comment by TaehoLi** [comment]
hi
How can I make it faster about inference time?

**Comment by SupreethN** [comment]
The current architecture uses ResNet101 backbone, so it's a big network and the inference time is high. If you want low inference times, you can trade-off the performance using lighter backbones such as ResNet-50. In that case, you should train a new architecture with a new backbone.

**Comment by TaehoLi** [comment]
thanks for your reply
then how can I make mask-rcnn model off about masks part?
I mean I just want to use this model for only getting rectangle hand bbox
I really appreciate for your help
