### ISSUE TITLE
trainning dataset can't be downloaded 

### ISSUE THREAD

**Issue by deep-practice** [SupreethN/Hand-CNN#8]

**Comment by SupreethN** [comment]
You can download from "http://vision.cs.stonybrook.edu/~supreeth/" in the Datasets section.

**Comment by deep-practice** [comment]
It returns no file found

**Comment by SupreethN** [comment]
I tried it now, I can download.

**Comment by deep-practice** [comment]
Emmmmm,me,too.SOOO strange.
